# Site settings
title:       MPL
email:       
author:      Mike P Land 
description: "interested in technology, economics, and livin in the future..."
baseurl:     ""
url:         "/"

# Google analytics
google_analytics: UA-13302760-2

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: lando2319
stackoverflow_id:
twitter_username: mikepland
google_plus_id:
linkedin_username:
angellist_username:
medium_id: mikepland
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
